workflows:
  expo-ios-simulator:
    name: Expo iOS Simulator Build
    environment:
      node: 18
      xcode: latest
    scripts:
      # Install dependencies
      - npm install --legacy-peer-deps
      # Generate ios/ directory (critical for Expo)
      - npx expo prebuild
      # Install iOS dependencies
      - cd ios && pod install && cd ..
      # Build and run on iOS Simulator
      - npx react-native run-ios --simulator="iPhone 15"
    artifacts:
      - ios/build/Build/Products/**/*.app