workflows:
  react-native-ios-simulator:
    name: React Native iOS Simulator Build
    environment:
      # Node.js version (required for React Native)
      node: 18
      # CocoaPods version (for iOS)
      cocoapods: default
    scripts:
      # Install dependencies
      - npm install --legacy-peer-deps
      # Install iOS dependencies
      - cd ios && pod install && cd ..
      # Build for iOS Simulator (Debug mode)
      - npx react-native run-ios --simulator="iPhone 15" --configuration Debug
    artifacts:
      # Optional: Save the built .app bundle (for debugging)
      - ios/build/Build/Products/**/*.app